In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [4]:
data = pd.read_csv("insurance_data.csv")
data

age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0

In [6]:
type(data["age"])#arrays

pandas.core.series.Series

In [8]:
type(data[["age"]])#dataframe

pandas.core.frame.DataFrame

In [9]:
type(data[[["age"]]])

KeyError: "None of [Index([('age',)], dtype='object')] are in the [columns]"

In [12]:
type(data.bought_insurance)

pandas.core.series.Series

In [15]:
x_train,x_test,y_train,y_test = train_test_split(data[["age"]],data.bought_insurance,test_size = 0.2, random_state = 1)#first two dimensional(age),next bought insurance one dimensional  #do remember

In [17]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [21]:
y_pred = model.predict(x_test)

In [22]:
y_pred

array([1, 1, 0, 1, 1, 0], dtype=int64)

In [23]:
y_test

17    1
14    1
18    0
3     0
23    1
10    0
Name: bought_insurance, dtype: int64

In [25]:
model.score(x_test,y_test)#the model already has the predicted values; using those values it compares with the y_test values and gives the accuracy

0.8333333333333334

In [26]:
#predict_proba

In [27]:
model.predict_proba(x_test)#0.04... is the probability that it belongs to class 0 and 0.95.. is the probability that it belongs to class 1

array([[0.04795632, 0.95204368],
       [0.15805894, 0.84194106],
       [0.93776133, 0.06223867],
       [0.10800643, 0.89199357],
       [0.25198743, 0.74801257],
       [0.94576637, 0.05423363]])

In [31]:
model.predict([[52]])#belongs to class 1 which is that they have taken insurance

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [32]:
model.predict([[21]])#they have not taken insurance

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)